coltypes=c(rep("character",2), rep("numeric",7))
powdat <- read.table("household_power_consumption.txt",sep=";",header=TRUE,colClasses=coltypes,na.strings="?")
powdat$Date <- as.Date(powdat$Date, format="%d/%m/%Y")
newdat <- subset(powdat, powdat$Date == as.Date("2007-02-01") | powdat$Date == as.Date("2007-02-02"))
newdat$dtime <- strptime(paste(as.character(newdat$Date),newdat$Time), format="%Y-%m-%d %H:%M:%S")
png(filename = "plot3.png", width = 480, height = 480)
plot(newdat$dtime,newdat$Sub_metering_1,type="l", ylab="Energy sub metering",xlab="")
lines(newdat$dtime,newdat$Sub_metering_2,type="l", col="red")
lines(newdat$dtime,newdat$Sub_metering_3,type="l", col="blue")
legend("topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=1, col = c("black","red","blue"))
dev.off()

